name: Latest blog post workflow
on:
  schedule:
    # 定时器配置
    - cron: "0 * * * *"
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5" # 获取链接数量
          feed_list: "https://waite.wang/sitemap.xml" # 博客订阅地址(RSS格式/Atom格式),,以逗号间隔不同的地址
          item_exec: "if (!post.title) post = null;" #to skip post that dont have title
          date_format: yy-mm-dd
