name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: zylele/social-readme@master
        with:
          blog_rss_link: https://waite.wang/rss.xml
          blog_limit: 5 # blog数量
          douban_name: sunguoqi
          douban_limit: 5 # 豆瓣最新动态数量
          douban_name: your douban username
